apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  name: {{ .Values.appName }}-ingress
  namespace: {{ .Values.ns }}
spec:
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.appName }}-service
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ .Values.hostName }}
    secretName: tls-secret