kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.ns }}
  name: {{ .Values.appName }}-service
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP